name: Run Basic Tests

on:
  pull_request:
    branches: [main]

jobs:
  #Oque vai ser feito nesta pipeline
  #Só teremos um job: rodar os testes
  cypress-run:
    # maquina que será executada
    runs-on: ubuntu-latest

    #Passo a passo para rodar os testes
    steps:
      #Clone do projeto
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      #Exemplo de execução no terminal
      - name: Instalar dependecias do projeto
        run: npm install 
      
      #Execução e configuração do projeto
      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}

      #Upload do relatório do mocha
      - name: Upload relatório
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: cypress\reports\html
