name: Run Basic Tests

on:
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Instalar dependências do projeto
        run: npm install

      - name: Rodar testes com Cypress
        run: npx cypress run
